import { Poppins } from "next/font/google";
import "./globals.css";

const popins = Poppins({
  weight: "400",
  variable: "--font-popins",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hire-X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${popins.variable} antialiased`}>{children}</body>
    </html>
  );
}
